repos:
  - repo: local
    hooks:
      - id: end-of-file-fixer
        name: End of File Fixer
        entry: end-of-file-fixer
        language: system
        types: [file]

      - id: semgrep-security-scan
        name: Semgrep Security Scan
        entry: semgrep --config auto
        language: system
        files: \.(py)$
        exclude: tests/
